### ISSUE TITLE
Dropwizard exits if Graylog server is not available

### ISSUE THREAD

**Issue by cw-dimedis** [gini/dropwizard-gelf#14]
I'd like my webserver to run even if the GELF host is unreachable. Is it possible to mark the appender as optional?

**Comment by joschi** [comment]
@cw-dimedis dropwizard-gelf is using [logback-gelf](https://github.com/Moocar/logback-gelf) which in turn is using GELF UDP by default. Since UDP is stateless, the GELF client can't possibly know whether the Graylog server is up or not.

This being said, I doubt that dropwizard-gelf is the reason your service doesn't start.

**Comment by cw-dimedis** [comment]
@joschi Oh, dropwizard-gelf was absolutely the reason Dropwizard stopped. Just use a running example and then change the config to use an unreachable URL. Your dropwizard process will exit once you try to log something during start-up.

But never mind, I fixed the problem by not using dropwizard-gelf anymore. Instead I'm using logstash-gelf now.

**Comment by joschi** [comment]
@cw-dimedis I've just tried to reproduce the issue but was unable to.

logback-gelf happily starts if the provided Graylog server is unreachable (e. g. doesn't run at all). What does not work, is using an invalid URL which cannot be resolved at all. In my opinion that's a feature and not a bug (in the sense of failing fast instead of silently ignoring errors).

**Comment by cw-dimedis** [comment]
@joschi By invalid URL you mean a URL that has a corrupt format? That was not my problem. I was trying to access a Graylog server that was behind a firewall, so a valid but unreachable URL. Did you test this in a dropwizard context?

Well, what you call a feature was a showstopper for me. In my opinion, logging is important, but not so important that I want my whole production server to shut down because it can't reach one logging target.

But please, I don't want to take up any of your time if you don't think this is important. As I said, I'm not using your (otherwise very useful) addon any longer. Thanks!

**Comment by joschi** [comment]
> By invalid URL you mean a URL that has a corrupt format?

Generally a hostname that cannot be resolved. It doesn't have to be an invalid hostname.

> Did you test this in a dropwizard context?

Yes.
